# Generated by Django 4.1.3 on 2022-12-31 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_tutorial_gratitude_tutorial_pomo1_tutorial_pomo2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='gratitude',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='priority',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='title',
            field=models.DateField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='todo1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='todo2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='todo3',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
