# Generated by Django 4.1.3 on 2023-03-24 01:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_alter_tutorial_description_alter_tutorial_gratitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
